"""Generate leagues/<name>.yaml from a live Sleeper league (v2 amendment A).

Baselines are DERIVED from the league's format — teams x starting slots x
flex demand — never copied from another league. The flex-demand split
(RB 45% / WR 45% / TE 10%) is a documented heuristic pending the empirical
own-league baselines of v2 item 2.2; superflex slots count as QB demand.
"""

from __future__ import annotations

import re
from pathlib import Path

from .sleeper import BASE, get_json

FLEX_SPLIT = {"RB": 0.45, "WR": 0.45, "TE": 0.10}
# pool depth beyond the replacement baseline, per position
POOL_PAD = {"QB": 16, "RB": 25, "WR": 20, "TE": 16, "K": 4, "DEF": 4}


def slot_counts(roster_positions: list[str]) -> tuple[dict[str, float], int]:
    """Positional starter demand (flex spread by FLEX_SPLIT) + bench size."""
    demand: dict[str, float] = {p: 0.0 for p in ("QB", "RB", "WR", "TE", "K", "DEF")}
    bench = 0
    for slot in roster_positions:
        s = slot.upper()
        if s in demand:
            demand[s] += 1
        elif s == "FLEX":
            for pos, share in FLEX_SPLIT.items():
                demand[pos] += share
        elif s in ("SUPER_FLEX", "SUPERFLEX"):
            demand["QB"] += 0.8          # superflex is a QB slot in practice
            demand["RB"] += 0.1
            demand["WR"] += 0.1
        elif s in ("REC_FLEX", "WRRB_FLEX"):
            for pos in ("WR", "RB"):
                demand[pos] += 0.5
        elif s == "BN":
            bench += 1
        # IDP/other slots ignored for baseline purposes
    return demand, bench


def derive_baselines(teams: int, roster_positions: list[str]) -> dict[str, int]:
    """Replacement level = league-wide startable demand, rounded, floored at
    one per team for K/DEF and at teams for onesie positions."""
    demand, _bench = slot_counts(roster_positions)
    out = {}
    for pos, d in demand.items():
        n = round(teams * d)
        out[pos] = max(n, teams if d > 0 else 0)
    return out


def derive_pool_sizes(baselines: dict[str, int]) -> dict[str, int]:
    return {pos: b + POOL_PAD.get(pos, 10) for pos, b in baselines.items() if b}


def onboard(league_id: str, username: str, name: str | None = None,
            root: Path = Path(".")) -> Path:
    lg = get_json(f"{BASE}/league/{league_id}")
    if not lg:
        raise SystemExit(f"league {league_id} not found on Sleeper")
    teams = int(lg["settings"].get("num_teams") or len(lg.get("roster_positions", [])) or 12)
    positions = lg.get("roster_positions") or []
    baselines = derive_baselines(teams, positions)
    pools = derive_pool_sizes(baselines)
    rounds = sum(1 for s in positions if s.upper() != "IR")
    slug = name or re.sub(r"[^a-z0-9]+", "-", str(lg.get("name", league_id)).lower()).strip("-")
    ppr = float(lg.get("scoring_settings", {}).get("rec", 0))

    y = [
        f"# {lg.get('name', '?')} — generated by `draftkit onboard` from live settings.",
        f"# {teams} teams · rec={ppr} · roster: {' '.join(positions)}",
        "# Baselines DERIVED from format (v2 amendment A) — verify then adjust.",
        "",
        f'league_id: "{league_id}"',
        f'draft_id: "{lg.get("draft_id") or ""}"',
        f"season: {lg.get('season', 2026)}",
        "stats_season: 2025",
        "",
        "me:",
        f"  username: {username}",
        "  user_id: null",
        "  draft_slot: null",
        "",
        "replacement_baselines:",
        *[f"  {pos}: {n}" for pos, n in baselines.items() if n],
        "",
        "pool_sizes:",
        *[f"  {pos}: {n}" for pos, n in pools.items()],
        "",
        "guardrails:",
        "  qb2_earliest_round: 10",
        "  te2_fall_picks: 12",
        "",
        "tiers:",
        "  break_z: 0.5",
        "  cliff_z: 1.0",
        f"  adp_include_within: {teams * max(rounds, 13)}",
        "",
        "tilts:",
        "  enabled: true",
        "  mid_te_fade: 0.08",
        "  nonrush_qb_fade: 0.08",
        "  rush_qb_late_boost: 0.08",
        "  elite_te_boost: 0.05",
        "  top5_regression: 0.10",
        "  cap: 0.10",
        "",
    ]
    out = root / "leagues" / f"{slug}.yaml"
    out.parent.mkdir(exist_ok=True)
    out.write_text("\n".join(y), encoding="utf-8")
    return out
